### PR TITLE
Check to see the given path exists

### PR DESCRIPTION
**Pull request by Artemid**
Fix for #4 "Check to see file exists"

### CODE REVIEW

**Comment by Artemid** [comment]
Sorry for crappy comment in commit didn't see style before commiting

**Comment by Jintin** [comment]
Since the test is failed, I think you can modify to pass the test.
1. the indent is tab base in andle.
2. isexist seems not found in some python version. I think you can use os.path.exists as an alternative.
https://docs.python.org/dev/library/os.path.html#os.path.exists
Thank you for your help.

**Comment by Artemid** [comment]
rebuild

**Comment by Jintin** [comment]
Thank you very much.

**Pull request merged**
